version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-${DEVELOPMENT_DB}}
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundler exec rails server -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - POSTGRES_DB=${DEVELOPMENT_DB}
    env_file:
      - .env
    depends_on:
      - db

  test:
    build: .
    entrypoint: ["/bin/bash", "/myapp/docker-entrypoint-test.sh"]
    volumes:
      - .:/myapp
    env_file: 
      - .env
    environment:
      - RAILS_ENV=test
      - POSTGRES_DB=${TEST_DB}
    depends_on:
      - db

volumes:
  postgres_data: